### ISSUE TITLE
province- or city-level data in past days?省级或者市级历史数据

### ISSUE THREAD

**Issue by caimiao0714** [GuangchuangYu/nCov2019#1]
Dear Dr. Yu,

Is it possible to get province- or city-level data in previous days? For example, can I get total confirmed cases in Hubei on Jan 30, 2019?

Thanks,
Miao

余教授好，

不知道有办法能够得到过往每个城市的数据？比如我想得到湖北各个城市2020年1月30号的数据。

谢谢！
蔡苗

**Comment by tungpatrick** [comment]
我大概看了一下, 主要是数据本身没有这个信息, 所以可能没办法呈现这个data. 可能可以找找别的dataset或是有人每天记录 自己算.

**Comment by caimiao0714** [comment]
> 我大概看了一下, 主要是数据本身没有这个信息, 所以可能没办法呈现这个data. 可能可以找找别的dataset或是有人每天记录 自己算.

好的，谢谢。主要是这个api好像是每天更新的，错过了也就没法看到过去的数据了。不知道有没有之前收集了数据的朋友可以分享下过去的数据。

**Comment by GuangchuangYu** [comment]
很多人求，然后我已经更新了，有这部分数据了。请看<https://mp.weixin.qq.com/s/lrQWGKj-mReWrxfi_4Sw9A>

求的人多，分享的人少，麻烦分享一下朋友圈呗。

**Comment by caimiao0714** [comment]
> 很多人求，然后我已经更新了，有这部分数据了。请看https://mp.weixin.qq.com/s/lrQWGKj-mReWrxfi_4Sw9A
> 
> 求的人多，分享的人少，麻烦分享一下朋友圈呗。

已经分享，感谢辛勤劳动~
