### ISSUE TITLE
library cannot work

### ISSUE THREAD

**Issue by yvonnelin223** [GuangchuangYu/nCov2019#100]
Hello,
the sample code is not working on my computer...

`> library(nCov2019)
> x <- get_nCov2019(lang='en')
Error in get_nCov2019(lang = "en") : unused argument (lang = "en")`

Do you know why?

**Comment by GuangchuangYu** [comment]
out-dated version.  The most recent version can be installed via `install.packages("nCov2019")`, see also <https://github.com/YuLab-SMU/nCov2019>.
