### ISSUE TITLE
有关中国疫情的数据更新问题

### ISSUE THREAD

**Issue by dingshikang** [GuangchuangYu/nCov2019#101]

**Comment by dingshikang** [comment]
老师，您号，有关中国疫情数据问题，这个是否没有更新呀？因为我跑出来截止2021-1-3是11万多，但目前中国已经13万多了？能够解答一下这个问题，谢谢

**Comment by GuangchuangYu** [comment]
请用<https://github.com/YuLab-SMU/nCov2019>这个版本。
