### ISSUE TITLE
Plot of China does not work well with the English version

### ISSUE THREAD

**Issue by tungpatrick** [GuangchuangYu/nCov2019#12]
I'm not sure how this could be fixed, but at the moment, the plot function for China and Chinese provinces do not work well with English names. It is probably because the names of the data have been changed to English, but the names on the map information is in Chinese.

**Comment by GuangchuangYu** [comment]
try:

```r
require(nCov2019)
x = get_nCov2019(lang='en')
plot(x)


require(chinamap)
cn = get_map_china()

## translate province 
cn$province <- trans_province(cn$province)

plot(x, region='china', chinamap=cn)
```

**Comment by tungpatrick** [comment]
This works! Thank you! Do you know if there is a way to make the test font smaller? Unfortunately, in English, the names are too large and become very messy.

**Comment by GuangchuangYu** [comment]
now you can use font.size and font.family to control the text label.
