### ISSUE TITLE
我已经更新到version 0.0.6，可是还是没办法提取历史数据

### ISSUE THREAD

**Issue by Nancy688** [GuangchuangYu/nCov2019#18]
请问各位大神，我已经更新到version 0.0.6，可是还是没办法提取历史数据
显示报错
> library("nCov2019", lib.loc="~/R/win-library/3.5")
> x<-load_nCov2019()
Error in readRDS(rds) : error reading from connection
In addition: Warning message:
In readRDS(rds) : invalid or incomplete compressed data
<img width="745" alt="issue" src="https://user-images.githubusercontent.com/60885886/74158375-ed466980-4c54-11ea-906f-9f658b21a09e.png">

请问怎么解决呀

**Comment by GuangchuangYu** [comment]
用R 3.6吧。

**Comment by zh-zhang1984** [comment]
Yu老师，非常感谢您的包，但有一一个疑问，那就是 load_nCov2019函数更新频率是多少？今天2-17下载的数据还是2-13号的.
> xhist <- load_nCov2019(lang='en')
> xhist
nCov2019 historical data 
last update: 2020-02-13 
而getget_nCov2019(）函数更新是比较及时的
> x <- get_nCov2019(lang='en')
> x
China (total confirmed cases): 70640
last update: 2020-02-17 15:45:09

**Comment by GuangchuangYu** [comment]
@Nancy688 现在是在线数据，也就是说更新了历史数据，你不需要更新包。有不少用户反馈Windows版本R 3.5，读在线数据有问题，更新到最新3.6.2就没问题。这包现在也是依赖R >= 3.6.0，这个包的新版本在旧版本的R已经装不上了，所以请更新R以及nCov2019包。

@zh-zhang1984 更新nCov2019 v >= 0.0.8，历史数据是最新的了。这一版本实现了自动更新机制。
