### ISSUE TITLE
提供一个代码优化的思路

### ISSUE THREAD

**Issue by fzgandw** [GuangchuangYu/nCov2019#2]
从您的公众号上看到您发的信息，就特别好奇是使用什么方法来提取数据（特别是当我发现 get_nCov2019函数只有三行代码时候我震惊了！！），拜读了一下您的代码，确实有非常大的收获，感谢Y叔的指点。

在对您的代码学习过程中，发现对于同一个参数多枚举判断时，可以考虑结合switch进行判断，例如：
summary.nCov2019 <- function(object, by = "total", ...) {
  by <- match.arg(by, c("total", "today"))
  if (by == "total") {
    return(object$chinaDayList)
  }
  return(object$chinaDayAddList)
}
类似于这样的情况下，可以考虑做下面的调整
summary.nCov2019 <- function(object, by = "total", ...) {
  switch(
    match.arg(by, c("total", "today")),
    "total" = object$total,
    "today" = object$today
  )
}
这样（也许）能增强代码的可读性。

2020.02.04 4点47分。。。

**Comment by pkglimmer** [comment]
兄弟 你还专门注册了个号吗

**Comment by fzgandw** [comment]
不，这是之前就注册的号，不过基本不怎么用。

**Comment by GuangchuangYu** [comment]
并不觉得有提升。thanks anyway.
