### ISSUE TITLE
 在世界地图上，显示每个国家确诊数目与读取的数据不一致

### ISSUE THREAD

**Issue by liuliuball45** [GuangchuangYu/nCov2019#20]
x = get_nCov2019(lang='en')读取数据后，
plot(x)
得到的data map. 与  x['global',] 中显示的不一致。
可以以美国为例， x['global',]  中美国的案例为13例，而在 data map 上对应美国的位置的显示为空白的。

**Comment by tungpatrick** [comment]
你好 我发了一个pull request. Once it is merged, plot(x) plot(x) 得到的data map会显示美国。

**Comment by tungpatrick** [comment]
这个问题已经修好了，你可以重新install nCov2019试试

**Comment by liuliuball45** [comment]
我试了。it works. thx for the support.
