### ISSUE TITLE
load_nCov2019() 历史数据只到10号？

### ISSUE THREAD

**Issue by CalibrationMe** [GuangchuangYu/nCov2019#23]
> library(nCov2019)
> load_nCov2019()
nCov2019 historical data 
last update: 2020-02-10 

这个是不是有问题？

**Comment by wantingallin** [comment]
对的，最新数据显示到了14号，但是历史数据还只是10号

**Comment by GuangchuangYu** [comment]
历史数据已经到13号，会持续更新的。
