### ISSUE TITLE
load_nCov2019()里的链接是不是错了？

### ISSUE THREAD

**Issue by ghost** [GuangchuangYu/nCov2019#25]
> library(nCov2019)
> x <- load_nCov2019()
Error in download.file(url, method = method, ...) : 
  cannot open URL 'https://gitee.com/GuangchuangYu/nCov2019-data/raw/master/nCov2019History.rds'

是不是应该是github.com?

**Comment by GuangchuangYu** [comment]
免得国内用户访问github有问题，放gitee。

**Comment by ghost** [comment]
你好，可是我下不了了，我得到上面放的error message，可能不能自动转过去？坐标国外有关？

**Comment by GuangchuangYu** [comment]
你点链接，如果在浏览器中不能下载，再反馈一下。

如果能下载，那可能R的问题。

**Comment by ghost** [comment]
> 你点链接，如果在浏览器中不能下载，再反馈一下。
> 
> 如果能下载，那可能R的问题。
你好，我直接点链接可以下载这个rds文件，但是在R里不行。。。
