### ISSUE TITLE
Issue on the number on heal and dead

### ISSUE THREAD

**Issue by jianvhuang** [GuangchuangYu/nCov2019#3]
Y叔，谢谢你的package。

我在查看数据的时候发现 daily heal 和 daily dead的数据和卫健委网站不一致。
似乎是 daily heal 和 daily dead的数据对调了。
我只看了武汉的数据，没有详细检查其他城市
http://wjw.hubei.gov.cn/bmdt/ztzl/fkxxgzbdgrfyyq/xxfb/202002/t20200203_2018274.shtml

**Comment by GuangchuangYu** [comment]
多谢，已修正。
