### ISSUE TITLE
Failed to install 'nCov2019' from GitHub

### ISSUE THREAD

**Issue by cicicamus** [GuangchuangYu/nCov2019#63]
Hi,

I am a newbie...don't know why I can't install this package. I have tried all 4 options but none of them worked. They all showed the same error: 

Error: Failed to install 'nCov2019' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘glue’

For example, if I choose option 1, it shows:

> remotes::install_github("GuangchuangYu/nCov2019")

Downloading GitHub repo GuangchuangYu/nCov2019@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                         
2: CRAN packages only          
3: None                        
4: Rcpp (1.0.3 -> 1.0.4) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
1
glue (NA    -> 1.3.2) [CRAN]
Rcpp (1.0.3 -> 1.0.4) [CRAN]
Installing 2 packages: glue, Rcpp

  There is a binary version available but the source version is later:
     binary source needs_compilation
Rcpp  1.0.3  1.0.4              TRUE

  Binaries will be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/glue_1.3.2.zip'
Content type 'application/zip' length 153935 bytes (150 KB)
downloaded 150 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/Rcpp_1.0.3.zip'
Content type 'application/zip' length 2990436 bytes (2.9 MB)
downloaded 2.9 MB

package ‘glue’ successfully unpacked and MD5 sums checked

Error: Failed to install 'nCov2019' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘glue’

Can someone help me please? 

Thank you in advance!

**Comment by huerqiang** [comment]
You can restart Rgui or Rstudio and then install nCov019. If there were still problems, you can delete the glue package first.

**Comment by cicicamus** [comment]
Thank you huerqiang! Problem solved!
