### ISSUE TITLE
Error in get_nCov2019, Error in rbind(deparse.level, ...)

### ISSUE THREAD

**Issue by nickrymantubb** [GuangchuangYu/nCov2019#69]
In get_nCov2019(), you call data <- .get_qq_data(), this now returns an error:

Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match 

I suspect the format of your fetched data has somehow changed?

**Comment by Alison-Lukan** [comment]
I am having the same issue

**Comment by dburela750** [comment]
I am having the same issue too

**Comment by nickrymantubb** [comment]
Seems to have been fixed
