### ISSUE TITLE
Dataset now missing the $global statistics

### ISSUE THREAD

**Issue by nickrymantubb** [GuangchuangYu/nCov2019#70]
Previously the dataset included an entry $global, which then had the worldwide statistics for different countries.  This now only includes one country as "China".

The plot() of the dataset (world map) no longer works - I assume because of the missing data?

**Comment by timze216** [comment]
Thanks you. 
Fixed. It should work after update.

**Comment by nickrymantubb** [comment]
Fixed in 86c5db8 - thank you :-)
