### ISSUE TITLE
Unable to get other countries in get_nCov2019() - global

### ISSUE THREAD

**Issue by coyin** [GuangchuangYu/nCov2019#72]
Looks like this feature recently broke:
```
current_data <- get_nCov2019()
current_data_global <- current_data$global 
```
current_data_global now only returns data for China, but not for other countries. I believe it used to return a list of countries and their respective cases. thanks!

**Comment by timze216** [comment]
Please update it. The latest version should work fine.

**Comment by coyin** [comment]
Perfect. Thank you!!
