### ISSUE TITLE
Real time data at province and city level

### ISSUE THREAD

**Issue by gexijin** [GuangchuangYu/nCov2019#8]
Thanks for fixing that issue so fast. I am still having issues at the city and province level: 

> remotes::install_github("GuangchuangYu/nCov2019")
> library(nCov2019)
> x <- get_nCov2019()
> x['广东', ]
Error: $ operator is invalid for atomic vectors

**Comment by GuangchuangYu** [comment]
fixed.

**Comment by gexijin** [comment]
Thank you!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
