### ISSUE TITLE
请问我用代码画的地图没颜色是为什么呢

### ISSUE THREAD

**Issue by Xizhi-Zhao** [GuangchuangYu/nCov2019#82]
library(mapproj)
remotes::install_github("GuangchuangYu/chinamap")
require(chinamap)
cn=get_map_china()
plot(x, region='china', chinamap=cn, continuous_scale=FALSE）

**Comment by GuangchuangYu** [comment]
画中国地图代码可参考在线文档<https://github.com/YuLab-SMU/nCov2019>.
