### ISSUE TITLE
Historical data for Beijing, Shanghai, Chongqing etc

### ISSUE THREAD

**Issue by gexijin** [GuangchuangYu/nCov2019#9]
No data is returned for Beijing, Shanghai etc.
> x <- load_nCov2019() #load historical data
> x['北京',]
 [1] province         city             time             cum_confirm      cum_heal         cum_dead        
 [7] 累计重症病例     累计危重病例     confirm          dead             heal             新增重症病例数量
[13] 新增危重病例数量 武汉接触史       来源链接         数据来源         公告中是否有病例 其他            
[19] X               
<0 rows> (or 0-length row.names)

**Comment by GuangchuangYu** [comment]
fixed.

**Comment by gexijin** [comment]
谢谢! 非常好的数据包!

我更新了Shiny app这个查询疫情的网页 http://www.bcloud.org/v/
可以看到有各个省，市的当前感染人数和增长趋势。还做了些简单的时间序列预测。直辖市有了各城区的数据。
从趋势看，这几天虽然确诊人数增加的速度稍微减慢， 但上升趋势很明显， 还在以每天10%的速度指数增长。一两个星期内好像不会结束。

Yu老师多保重!


Sent from my T-Mobile 4G LTE Device



-------- Original message --------

**Comment by GuangchuangYu** [comment]
要不要简单写个文，在我公众号上介绍一下你这个shiny app?

Steven Ge <notifications@github.com> 于 2020年2月8日周六 13:40写道：

**Comment by gexijin** [comment]
Y叔，
那太好了。我回头写好发给您。

可以直接给您邮件吗？
你的包做的太好了。地图直接就出。不知道能不能把国内的边界图文件发给我一份，或提供一个链接。找了半天也没找到。

m = sf::st_read("../Downloads/市界.shp")
plot(x, region='湖北', chinamap=m)
多谢！
锡金

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by GuangchuangYu** [comment]
链接: https://pan.baidu.com/s/1ZVWC7nEtIi8F7-2x-e1NZw 提取码: sx8r 复制这段内容后打开百度网盘手机App，操作更方便哦


 
---Original---

**Comment by gexijin** [comment]
余老师，
谢谢！
是必须有百度网盘的账号才能下载吗？
我折腾半天，没有国内手机号，确认码收不到，很难下载。
我再试试。您要是可以改成直接下载的话那就更好了。
多谢
锡金

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by gexijin** [comment]
余老师，
文件已经下载下来了。谢谢。新的地图功能也加到Shiny APP 了。你的R包太强了。

直辖市的地图是不是不支持？
m = sf::st_read("map/shijie.shp")
plot(x, region='北京', chinamap=m)
北京的出错。
上海和重庆的出全国地图。
这个问题不大。做好有个NULL的值return了。


我很简单的写了一些文件，见附件。您随便改。

谢谢。多保重！
锡金


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10


From: Ge, Xijin <Xijin.Ge@sdstate.edu>
Sent: Saturday, February 8, 2020 10:24:22 AM
To: gcyu1@smu.edu.cn <gcyu1@smu.edu.cn>; GuangchuangYu/nCov2019 <reply@reply.github.com>
Subject: RE: [GuangchuangYu/nCov2019] Historical data for Beijing, Shanghai, Chongqing etc (#9)


Y叔，

那太好了。我回头写好发给您。



可以直接给您邮件吗？

你的包做的太好了。地图直接就出。不知道能不能把国内的边界图文件发给我一份，或提供一个链接。找了半天也没找到。



m = sf::st_read("../Downloads/市界.shp")
plot(x, region='湖北', chinamap=m)

多谢！

锡金



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by GuangchuangYu** [comment]
没有附件，你回复的是github，附件不会上来，发guangchuangyu@gmail.com

**Comment by GuangchuangYu** [comment]
因为地图是市界的，所以北京上海这些，画也只出一块，不会出按区来分的（数据是按区的，所以merge的时候，就丢了）。这个先不管吧，画一整块的，也没意思，想画出区的，得找以县为单位的地图了。
