### ISSUE TITLE
label_cut needs adjusting; automatic suggestion

### ISSUE THREAD

**Issue by DannyQuah** [GuangchuangYu/nCov2019#92]
Thank you for this really useful collection of data and code. A gentle suggestion on example.R:

In line 18 label_cut=700 no longer works given the increase in confirmed case numbers generally. The code breaks as `d$cum_confirm < label_cut` returns a null-dimensioned vector. I replaced the hard-coding with 

```
label_cut = median(dd$cum_confirm) 
```

but others might prefer something else.

(I believe this also fixes Issue #78, @russell9)

**Comment by GuangchuangYu** [comment]
updated `example.R` is located in <https://github.com/YuLab-SMU/nCov2019/blob/master/example.R>.
